export const checkUser = async (req,res) => {
    try {
        
    } catch (error) {
        console.error(error)
    }
}